
name: Checkout and setup
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
